# Generated by Django 2.2.1 on 2019-06-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
